name: pydelmod
channels:
  - cadwr-dms
  - pyviz
  - defaults
  - plotly
  - conda-forge
dependencies:
  - python=3.7
  # first our packages
  - vtools3
  - schimpy
  # then basics
  - numpy 
  - scipy
  - pandas
  - xarray
  - netcdf4
  - cfunits
  - scipy
  - statsmodels
  - gdal
  - geopandas
  - shapely
  - xlrd
  # more stuff
  - beautifulsoup4
  - palettable
  - rtree
  - sympy
  # then plot stuff
  - matplotlib
  - seaborn
  - holoviews
  - hvplot
  - jupyter
  - networkx
  - ipyleaflet
  - ipywidgets
  # dev stuff
  - pytest-runner
  - sphinx
  - nbsphinx
  - numpydoc
  - sphinx-argparse
  - spyder-kernels
  - jupyter_contrib_nbextensions
  - ipysheet
